main: me.jasonhorkles.nosleep.NoSleep
name: NoSleep
description: Prevent players from sleeping
version: %VERSION%
author: JasonHorkles
api-version: '1.21'

commands:
  nosleep:
    description: "Prevent players from sleeping for the night"
    aliases: [ "preventsleep" ]
    usage: "§cYou must be in the overworld to prevent sleep!"
  
  allowsleep:
    description: "Allow players to sleep again"
